### PR TITLE
Task map validation

### PR DESCRIPTION
**Pull request by juhoeerola**
While drawing a new connection:
- tasks that can not be connected to are grayed out
- handles that can accept the connection are highlighted

While dragging task from synergy group to another, unavailable groups are grayed out.

On the server side, the graph is validated each time new relations are added.
Deleting relations will never invalidate the graph.

### CODE REVIEW

**Review by AleksiKytola — APPROVED** [review]
Looked good in the demo, I'm not particularly familiar with the task map but on a quick glance the code looks good

**Review by PatricKangasmaki — CHANGES_REQUESTED** [review]
You can currently drag relations to tasks that are in the same group (Even though the highlight says you can't)

image


image

**Comment by juhoeerola** [comment]
> You can currently drag relations to tasks that are in the same group

The backend correctly rejects this for me, so I couldn't reproduce this.

But sure the frontend shouldn't even try sending that request, I'll fix that.

**Comment by PatricKangasmaki** [comment]
> The backend correctly rejects this for me

Ah, I probably had old server up from some other branch

**Comment by juhoeerola** [comment]
Should be fixed now.

The state was clearing between the connection ending and validation, which would suggest that there are some unnecessary rendering happening. But that should no longer affect the correctness.

**Review by PatricKangasmaki — APPROVED** [review]

**Pull request merged**
