### PR TITLE
Fix occasional customer corruption on update

### PR DESCRIPTION
**Pull request by PatricKangasmaki**
Fix an issue where occasionally customer could get corrupted in the controller, causing the updating customers to stop working

### CODE REVIEW

**Review by juhoeerola — CHANGES_REQUESTED** [review]
As mentioned in the other comments, the logic works for the current frontend, but allowing partial patching would be desirable.

The previous logic was:
- find the correct customer
- patch the properties excluding representatives
- if no representatives
  - return patched customer, or false if nothing was patched
- patch representatives
- return patched customer

Ps. it actually seems to be the typescript update... ~I'm pretty sure the change in behaviour was introduced in the knex/objection.js update~

**Comment by PatricKangasmaki** [comment]
Would this solution work better?

New logic:

- Find correct customer -> return false if not found
- If no representatives -> return updated customer (If nothing was patched -> return false)
- Patch representatives
- If none of the customer values (name, email, color, weight) were updated, return customer with new fetched representatives
- Patch customer and fetch updated representatives

Now you can update values only, representatives only or both at the same time.

**Review by juhoeerola — APPROVED** [review]

**Comment by juhoeerola** [comment]
Seems good!

Could you add  some tests for the customer routes, to ensure it keeps working

**Comment by PatricKangasmaki** [comment]
> Could you add some tests for the customer routes, to ensure it keeps working

That sounds like a good idea, I'll start working on the tests and make a new pr when they're ready 👍

**Pull request merged**
