### PR TITLE
Add margin between multiple scrollbars

### PR DESCRIPTION
**Pull request by IidaKainu**
https://trello.com/c/S5O0WEsp/705-marginia-scollbareihin
I would have added space with margins, but they seemed to have no effect on the scrollbar. So implemented this with borders instead.

### CODE REVIEW

**Comment by IidaKainu** [comment]
Forgot horizontal scrollbars exist. Now border is added to all sides

**Comment by juhoeerola** [comment]
I think it would be better to add small padding to the scrollable container in the places where the bars would be next to each other.

The appearance becomes a bit wild with the border as there's now 3 shades of gray in the bar (handle, background, border), and the page background is likely one more shade.

**Review by juhoeerola — APPROVED** [review]
Seems good 👍 

The overview's duplicate vertical scroll didn't make much sense, so I removed that. Check that I didn't mess it up somehow.

**Comment by IidaKainu** [comment]
> The overview's duplicate vertical scroll didn't make much sense, so I removed that. Check that I didn't mess it up somehow.

Great! horizontal scroll still works as usual so should be ok

**Pull request merged**
