### PR TITLE
Move project overview page to higher level router

### PR DESCRIPTION
**Pull request by IidaKainu**
- Changed route from 'roadmap/:selectedroadmapId/overview' to '/overview'.
- The sidebar will no longer show on the overview page.
- chosenRoadmap is removed from Localstorage when moving to the overview page, as no roadmap should be selected.

### CODE REVIEW

**Comment by juhoeerola** [comment]
The roadmap in local storage should go away eventually, when the "favourite roadmap" functionality is implemented.
Now the dropdown selector still shows the "selected" roadmap, as it takes it from the state, not from local storage, so the selection should also be cleared from the state.

Also the whole page is scrolling, instead of just the content (like on other pages). It would probably be nicer if the navbar stayed still, both horizontally and vertically. Also the page header could be stationary, so it doesn't disappear when scrolling sideways.

Having the logo in the top left corner, where it would be with the side bar, might also add some nice consistency between the pages.

How it looks  now:
before

How it might look with the changes:
after

**Comment by IidaKainu** [comment]
> the selection should also be cleared from the state

Added! 
Style fixes: 
- the page header  and navbar stays in place
- added visdomLogo 

The vertical scroll looks quite wonky now tough. Also reloading the page shows the incorrect navbar. I'll try to fix these tomorrow.

**Comment by IidaKainu** [comment]
Looks like I forgot requireLogin() from the component. The page reload works as intended now.
I am not sure if I'll be able to do much about the double vertical scrollbar with the current CSS approach.

**Review by juhoeerola — CHANGES_REQUESTED** [review]
The selector widget does not reflect the clearing of the selected roadmap, this should have `else` setting the selection back to the initial placeholder.

https://github.com/Vincit/VISDOM-Roadmapper/blob/93fc9fe4a8ab9c50be5c50a5f68c236572ba2449/frontend/src/components/RoadmapSelectorWidget.tsx#L39-L47

Otherwise looks great 👍 

The double vertical scroll bars are also on the other pages, so that could be a separate issue to clean up. Vertical scroll also shouldn't be as common to have on this page.

**Review by juhoeerola — APPROVED** [review]

**Pull request merged**
