### PR TITLE
Fixed some text in landingpage

### PR DESCRIPTION
**Pull request by DanielMakinen**
Small fix. Time estimation was written twice in the feature-list.

### CODE REVIEW

**Review by PatricKangasmaki — APPROVED** [review]
👍

**Comment by juhoeerola** [comment]
Just a note on the commit message style: It's best to keep the subject line short and to the point. There is plenty of space to elaborate in the body paragraphs. Also present, instead of past, tense is usually preferred for the subject line ("Fix" instead of "Fixed").

For example:

```
Remove duplicate paragraph from landing page

More explanation here if needed, multiple paragraphs is fine. Wrap
lines at appropriate length, so they stay nice to read.
```

**Comment by PatricKangasmaki** [comment]
Good point from @juhoeerola, here's a good read about git commits as well (though juho already explained the key points)
https://cbea.ms/git-commit/

**Comment by juhoeerola** [comment]
There is also a great git course in univincity that goes to many other aspects of using git as well

**Comment by DanielMakinen** [comment]
Thanks for feedback! I read the article and will later go through the univincity git-course.

I changed the commit message to be more concise.

**Pull request merged**
